# Generated by Django 3.2.13 on 2022-12-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('L', 'Libero'), ('H', 'Hitter'), ('S', 'Setter')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Player name', max_length=100, unique=True)),
                ('position', models.ManyToManyField(to='lineups.Position')),
            ],
        ),
    ]
