# Generated by Django 3.2.13 on 2022-12-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
