# Generated by Django 3.2.13 on 2022-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favorite_ice_cream',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ManyToManyField(null=True, to='lineups.Position'),
        ),
    ]
