# Generated by Django 3.2.13 on 2022-12-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0004_auto_20221219_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='favorite_ice_cream',
            field=models.CharField(blank=True, default='Chocolate', max_length=50),
            preserve_default=False,
        ),
    ]
